# sessions.py

SESSIONS_CATEGORIES = {
    "Monuments et Lieux Emblématiques": {
        "Le patrimoine palatial et institutionnel": [
            "Louvre - Rivoli",
            "Palais Royal - Musée du Louvre",
            "Invalides",
            "Panthéon",
            "Odéon",
            "Château de Vincennes",
        ],
        "L'architecture religieuse": [
            "Madeleine",
            "Saint-Sulpice",
            "Notre-Dame-des-Champs",
            "Trinité - d'Estienne d'Orves",
            "Saint-Augustin",
            "Saint-Philippe du Roule",
        ],
        "L'ingénierie et l'industrie": [
            "Arts et Métiers",
            "Glacière",
            "Mouton-Duvernet",
            "Pont Neuf",
            "Bourse",
        ],
    },
    "Topographie et Urbanisme": {
        "Architecture urbaine : Les grandes gares": [
            "Gare du Nord",
            "Gare de l'Est",
            "Gare de Lyon",
            "Gare d'Austerlitz",
            "Gare Saint-Lazare",
            "Montparnasse - Bienvenüe",
        ],
        "Les Portes de Paris (Nord et Est)": [
            "Porte de Clignancourt",
            "Porte de la Chapelle",
            "Porte de la Villette",
            "Porte de Pantin",
            "Porte des Lilas",
            "Porte de Bagnolet",
            "Porte de Montreuil",
            "Porte de Vincennes",
            "Porte Dorée",
            "Porte de Charenton",
        ],
        "Les Portes de Paris (Sud et Ouest)": [
            "Porte d'Italie",
            "Porte de Choisy",
            "Porte d'Ivry",
            "Porte d'Orléans",
            "Porte de Vanves",
            "Porte de Versailles",
            "Porte de Saint-Cloud",
            "Porte d'Auteuil",
            "Porte Dauphine",
            "Porte Maillot",
            "Porte de Champerret",
            "Porte de Clichy",
            "Porte de Saint-Ouen",
        ],
    },
    "Histoire et Politique": {
        "Révolution et République": [
            "Bastille",
            "Concorde",
            "Convention",
            "Nation",
            "République",
            "Robespierre",
        ],
        "Les Femmes Illustres": [
            "Louise Michel",
            "Pierre et Marie Curie",
            "Bagneux - Lucie Aubrac",
            "Barbara",
            "Europe - Simone Veil",
            "Gaîté - Joséphine Baker",
            "Boucicaut",
        ],
        "Les figures de la Résistance": [
            "Jean Moulin",
            "Guy Môquet",
            "Corentin Celton",
            "Jacques Bonsergent",
            "Marx Dormoy",
            "Corentin Cariou",
            "Colonel Fabien",
            "Charles Michels",
        ],
        "Les victoires et batailles militaires": [
            "Austerlitz",
            "Iéna",
            "Wagram",
            "Solférino",
            "Bir-Hakeim",
            "Stalingrad",
            "Crimée",
            "Campo-Formio",
            "Pyramides",
        ],
    },
    "Arts et Culture": {
        "Écrivains et Philosophes": [
            "Victor Hugo",
            "Alexandre Dumas",
            "Avenue Émile Zola",
            "Voltaire",
            "Edgar Quinet",
            "Anatole France",
        ],
        "Peintres, Sculpteurs et Poètes": [
            "Pigalle",
            "Falguière",
            "Aimé Césaire",
            "Bobigny - Pablo Picasso",
            "Bobigny - Pantin - Raymond Queneau",
            "Goncourt",
            "Michel-Ange - Auteuil",
            "Malakoff - Rue Étienne Dolet",
        ],
    },
    "Sciences et Techniques": {
        "Mathématiques, Physique et Biologie": [
            "Pasteur",
            "Place Monge",
            "Réaumur - Sébastopol",
            "Raspail",
            "Lamarck - Caulaincourt",
            "Jussieu",
            "Parmentier",
            "Corvisart",
            "Brochant",
        ]
    },
}
